// flow-typed signature: 1fb1a352a5a1adffe6fb8758fe918b87
// flow-typed version: <<STUB>>/styled-components_v2.1.1/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components' {
  declare module.exports: any
}
